
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRadioButton;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Beyza
 */
public class CandidateSelection extends javax.swing.JFrame {
    Statistics value = new Statistics();
    JPanel ui= new JPanel(new GridLayout(0,1,4,4));
    String[] partyArray = new String[28];
    private JCheckBox boxes[];
    private String[] participant;
    private String partyName;
    private int partyIndex;

    public CandidateSelection(int partyIndex) {
        this.partyIndex = partyIndex;
    }

    public int getPartyIndex() {
        return partyIndex;
    }

    public void setPartyIndex(int partyIndex) {
        this.partyIndex = partyIndex;
    }
    
    public CandidateSelection(String partyName) {
        this.partyName = partyName;
    }

    public String getPartyName() {
        return partyName;
    }

    public void setPartyName(String partyName) {
        this.partyName = partyName;
    }
    
    public String[] getParticipant() {
        return participant;
    }

    public void setParticipant(String[] participant) {
        this.participant = participant;
    }

    public CandidateSelection(String[] participant) {
        this.participant = participant;
    }
       
    public CandidateSelection() {
        initComponents();
        setContentPane(ui);  //https://www.decodejava.com/java-jscrollpane.htm
        boxes = new JCheckBox[28];
        add(buttonVote);
        add(buttonBack);
        setVisible(true);
        setResizable(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
 
    public String[] partyFunction(String [][] array,int index,String partyName){ 
        setPartyName(partyName);
        setPartyIndex(index);
        for(int i=0 ;i<28;i++){
            partyArray[i] = array[index][i]; 
            createrCheckBox(i);
            //seçilen partinin adaylarını aldım.
            
        }
        
        return partyArray;
    }
     public void createrCheckBox(int i) {
        boxes[i] = new JCheckBox(partyArray[i]);
       // boxes[i].setBorder(new EmptyBorder(0,0,0,0));
        ui.add(boxes[i]);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVote = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonVote.setText("Vote");
        buttonVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoteActionPerformed(evt);
            }
        });

        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(buttonVote, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(848, 848, 848)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVote)
                    .addComponent(buttonBack))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        setVisible(false); 
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoteActionPerformed
        // TODO add your handling code here:
        
        String candidateNames = "";
            
        for (JCheckBox checkBox : boxes) {
            if (checkBox.isSelected()) {
                candidateNames= candidateNames + "-" + checkBox.getText();
            }
        }
        List <String> chosenCandidates = new ArrayList<> ();
        Vote userVote = new Vote(this.partyName,this.partyIndex,this.participant,candidateNames);
        try {
            userVote.SubmitVote();
        } catch (IOException ex) {
            Logger.getLogger(CandidateSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
       System.out.println(Arrays.deepToString(chosenCandidates.toArray()));
        Main temp = new Main();
        temp.setVisible(true);
        temp.setState(java.awt.Frame.NORMAL);             
    }//GEN-LAST:event_buttonVoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidateSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidateSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidateSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidateSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CandidateSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonVote;
    // End of variables declaration//GEN-END:variables

  
}
