import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JFrame;
import javax.swing.JRadioButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Beyza
 */
public class PartySelection extends javax.swing.JFrame {
    private String[] participant;
    /**
     * Creates new form PartySelection
     */
    public PartySelection() {
        initComponents();
    }

    public String[] getParticipant() {
        return participant;
    }

    public void setParticipant(String[] participant) {
        this.participant = participant;
    }

    public PartySelection(String[] participant) {
        this.participant = participant;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        buttonBornova = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonKaraburun = new javax.swing.JRadioButton();
        buttonSigacik = new javax.swing.JRadioButton();
        buttonUrla = new javax.swing.JRadioButton();
        buttonKordonboyu = new javax.swing.JRadioButton();
        buttonSakran = new javax.swing.JRadioButton();
        buttonCesme = new javax.swing.JRadioButton();
        buttonOdemis = new javax.swing.JRadioButton();
        buttonOzdere = new javax.swing.JRadioButton();
        buttonFoca = new javax.swing.JRadioButton();
        buttonDikili = new javax.swing.JRadioButton();
        buttonGumuldur = new javax.swing.JRadioButton();
        buttonCont = new javax.swing.JButton();
        buttonNone = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Party Selection");

        buttonGroup.add(buttonBornova);
        buttonBornova.setText("Bornova Partisi");
        buttonBornova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBornovaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 24)); // NOI18N
        jLabel1.setText("Which party will you vote for?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        buttonGroup.add(buttonKaraburun);
        buttonKaraburun.setText("Karaburun Partisi");
        buttonKaraburun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKaraburunActionPerformed(evt);
            }
        });

        buttonGroup.add(buttonSigacik);
        buttonSigacik.setText("Sigacik Partisi");

        buttonGroup.add(buttonUrla);
        buttonUrla.setText("Urla Partisi");
        buttonUrla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUrlaActionPerformed(evt);
            }
        });

        buttonGroup.add(buttonKordonboyu);
        buttonKordonboyu.setText("Kordonboyu Partisi");

        buttonGroup.add(buttonSakran);
        buttonSakran.setText("Sakran Partisi ");

        buttonGroup.add(buttonCesme);
        buttonCesme.setText("Cesme Partisi");

        buttonGroup.add(buttonOdemis);
        buttonOdemis.setText("Odemis Partisi");

        buttonGroup.add(buttonOzdere);
        buttonOzdere.setText("Ozdere Partisi");

        buttonGroup.add(buttonFoca);
        buttonFoca.setText("Foca Partisi");

        buttonGroup.add(buttonDikili);
        buttonDikili.setText("Dikili Partisi");

        buttonGroup.add(buttonGumuldur);
        buttonGumuldur.setText("Gumuldur Partisi");
        buttonGumuldur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGumuldurActionPerformed(evt);
            }
        });

        buttonCont.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 13)); // NOI18N
        buttonCont.setText("Continue");
        buttonCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContActionPerformed(evt);
            }
        });

        buttonGroup.add(buttonNone);
        buttonNone.setText("None");
        buttonNone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonUrla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSigacik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonKaraburun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonBornova, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(buttonKordonboyu)
                            .addComponent(buttonFoca)
                            .addComponent(buttonDikili)
                            .addComponent(buttonGumuldur)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonCesme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSakran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(buttonOdemis)
                            .addComponent(buttonOzdere)
                            .addComponent(buttonNone)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(buttonCont, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBornova)
                .addGap(18, 18, 18)
                .addComponent(buttonKaraburun)
                .addGap(18, 18, 18)
                .addComponent(buttonSigacik)
                .addGap(18, 18, 18)
                .addComponent(buttonUrla)
                .addGap(18, 18, 18)
                .addComponent(buttonKordonboyu)
                .addGap(18, 18, 18)
                .addComponent(buttonSakran)
                .addGap(18, 18, 18)
                .addComponent(buttonCesme)
                .addGap(18, 18, 18)
                .addComponent(buttonOdemis)
                .addGap(18, 18, 18)
                .addComponent(buttonOzdere)
                .addGap(18, 18, 18)
                .addComponent(buttonFoca)
                .addGap(18, 18, 18)
                .addComponent(buttonDikili)
                .addGap(18, 18, 18)
                .addComponent(buttonGumuldur)
                .addGap(18, 18, 18)
                .addComponent(buttonNone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(buttonCont, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGumuldurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGumuldurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGumuldurActionPerformed

    private void buttonBornovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBornovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBornovaActionPerformed

    private void buttonKaraburunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKaraburunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonKaraburunActionPerformed

    private void buttonUrlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUrlaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUrlaActionPerformed

    private void buttonContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContActionPerformed
        int partyIndex = -1;
        String  partyName=" ";
        //https://www.youtube.com/watch?v=eyWXZ3gEfGQ&t=384s
        buttonCont.addActionListener(new ActionListener(){
           public void actionPerformed(ActionEvent arg0){
               Enumeration<AbstractButton> bg = buttonGroup.getElements();
               while(bg.hasMoreElements()){
                   JRadioButton jrd =(JRadioButton) bg.nextElement();
                   if(jrd.isSelected()){
                       System.out.println(jrd.getText());
                       
                   }
               }
              }
           });
      for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
        AbstractButton button = buttons.nextElement();
        if (button.isSelected()) {
                partyName = button.getText(); //seçilen partiyi çektim
        }
        }
      
       Candidate takingCandidates = new Candidate();
       takingCandidates.setSelectedParty(partyName); // seçilen partimi Candidate classına gönerdim
      
       //System.out.println(" name"+partyName);
       partyIndex = takingCandidates.chosenParty(); //partinin indeksini hesaplatıp adayları çekmek için
      
        
       if(partyIndex == -1){ //hiçbir parti seçmeyip NONE seçerse
            PartyIndependent tempOther = new PartyIndependent();  
            String [] candidateList = takingCandidates.candidateList();
            tempOther.candidateFunction(candidateList);
            tempOther.setParticipant(this.participant);
            tempOther.setVisible(true);
            tempOther.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
        else{ // parti seçip adaylarına oy vermek için 
            String [][] candidateArray = takingCandidates.seperatingCandidates();
            CandidateSelection temp = new CandidateSelection();
            temp.partyFunction(candidateArray,partyIndex,partyName);
            temp.setParticipant(this.participant);
            temp.setVisible(true);
            temp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
 
       


    }//GEN-LAST:event_buttonContActionPerformed

    private void buttonNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNoneActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonNoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartySelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartySelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartySelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartySelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartySelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buttonBornova;
    private javax.swing.JRadioButton buttonCesme;
    private javax.swing.JButton buttonCont;
    private javax.swing.JRadioButton buttonDikili;
    private javax.swing.JRadioButton buttonFoca;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton buttonGumuldur;
    private javax.swing.JRadioButton buttonKaraburun;
    private javax.swing.JRadioButton buttonKordonboyu;
    private javax.swing.JRadioButton buttonNone;
    private javax.swing.JRadioButton buttonOdemis;
    private javax.swing.JRadioButton buttonOzdere;
    private javax.swing.JRadioButton buttonSakran;
    private javax.swing.JRadioButton buttonSigacik;
    private javax.swing.JRadioButton buttonUrla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
